### ISSUE TITLE
 this.didDocument.readMessage(handler) error handling discussion

### ISSUE THREAD

**Issue by Mastaleru** [PrivateSky/OpenDSU#31]
I have the following code 

```
listenForMessages(callback) {
         this.didDocument.readMessage((err, decryptedMessage) => {
            if (err) {
                console.error(err);
            } else{
               callback(err, decryptedMessage);
            }
             this.listenForMessages(callback);
        });
}
```

If I refresh the browser while I have a pending request (from the _readMessage_ call) an error will be thrown and it will enter in an infinite loop of throwing fetch errors like the following:
![image](https://user-images.githubusercontent.com/1469129/153066388-78338ee0-ae26-4340-ae09-5e949ab78477.png) 

forcing me to return if an error occurs and to not call again the  _this.didDocument.readMessage_ method

I'm not sure that this kind of errors, connection  errors should be bubbled up to this, or maybe them should be wrapped in error types.

**Comment by salboaie** [comment]
API changed
